version: '3.1'

services:
    database:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example

    suntrackerino:
        build: .
        ports:
            - 8080:3000
        environment: 
            HOST: database
        links:
            - database
        depends_on: 
            - database